# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180205_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'products/'),
        ),
    ]
