# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180206_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=b'slug-url-share', unique=True),
        ),
    ]
